In [1]:
from datetime import datetime
import time

In [2]:
import os

# Initialize PySpark
exec(open(os.path.join(os.environ["SPARK_HOME"], "python/pyspark/shell.py")).read())

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.2.0
      /_/

Using Python version 3.6.0 (default, Dec 23 2016 12:22:00)
SparkSession available as 'spark'.

In [ ]:
#from pyspark import SparkContext

In [ ]:
"""
import findspark
findspark.init()

import pyspark
import random
sc = pyspark.SparkContext(appName="Test")
"""

In [3]:
### some useful imports used throughout this notebook
from pyspark.sql import *
from pyspark.sql.types import *
import pyspark.sql.functions as F

In [4]:
sqlCtx = SQLContext(sc)

In [5]:
#sqlCtx.setConf("spark.local.dir", "/media/andraa/10160545101605452/spark")

In [6]:
logs = (sqlCtx
      .read.format('parquet')
      .options(header='true', inferschema='true')
      .load('/media/andraa/10160545101605452/kaggle/WSDM-kaggle/data/user_logs.parquet'))

In [7]:
"""
logs = (sqlCtx
      .read.format('com.databricks.spark.csv')
      .options(header='true', inferschema='true')
      .load('/media/andraa/10160545101605452/kaggle/WSDM-kaggle/data/user_logs_sample_2G.csv'))
      """

"\nlogs = (sqlCtx\n      .read.format('com.databricks.spark.csv')\n      .options(header='true', inferschema='true')\n      .load('/media/andraa/10160545101605452/kaggle/WSDM-kaggle/data/user_logs_sample_2G.csv'))\n      "

In [8]:
"""
logs.write.parquet('/media/andraa/10160545101605452/kaggle/WSDM-kaggle/data/user_logs_sample_2G.parquet')
"""

"\nlogs.write.parquet('/media/andraa/10160545101605452/kaggle/WSDM-kaggle/data/user_logs_sample_2G.parquet')\n"

In [9]:
logs.printSchema()

root
 |-- msno: string (nullable = true)
 |-- date: integer (nullable = true)
 |-- num_25: integer (nullable = true)
 |-- num_50: integer (nullable = true)
 |-- num_75: integer (nullable = true)
 |-- num_985: integer (nullable = true)
 |-- num_100: integer (nullable = true)
 |-- num_unq: integer (nullable = true)
 |-- total_secs: double (nullable = true)

In [10]:
logs.show(20)

+--------------------+--------+------+------+------+-------+-------+-------+----------+
|                msno|    date|num_25|num_50|num_75|num_985|num_100|num_unq|total_secs|
+--------------------+--------+------+------+------+-------+-------+-------+----------+
|L7Amv5Vawu+R52zRd...|20160612|     0|     1|     2|      0|      5|      6|  1438.998|
|L7Amv5Vawu+R52zRd...|20160805|     6|     0|     0|      1|     13|     16|  4014.902|
|L7Amv5Vawu+R52zRd...|20160926|     0|     0|     0|      1|     11|     12|   3642.45|
|L7Amv5Vawu+R52zRd...|20161123|     1|     0|     0|      2|     36|     22|   9738.31|
|L7Amv5Vawu+R52zRd...|20170114|     0|     0|     0|      1|     12|     12|  3176.986|
|6RDXC1K76TAc/Emo4...|20151106|     7|     1|     0|      3|     25|     34|  6497.174|
|6RDXC1K76TAc/Emo4...|20160110|     8|     0|     1|      0|     28|     34|  7434.636|
|6RDXC1K76TAc/Emo4...|20160411|     0|     0|     0|      0|      6|      6|  1689.972|
|6RDXC1K76TAc/Emo4...|20160621|     2|     3|     0|      0|      6|      9|  1826.677|
|6RDXC1K76TAc/Emo4...|20160925|     3|     0|     0|      0|      9|     12|  2303.381|
|6RDXC1K76TAc/Emo4...|20161123|     7|     4|     0|      0|      4|     15|  1528.046|
|xpNjjyiJvP16vv0XG...|20151201|     0|     0|     1|      0|      0|      1|   126.851|
|xpNjjyiJvP16vv0XG...|20160310|     1|     0|     2|      0|     19|     22|  5801.389|
|xpNjjyiJvP16vv0XG...|20160905|     0|     0|     0|      0|      2|      2|   542.406|
|xpNjjyiJvP16vv0XG...|20170214|     2|     1|     1|      0|     21|     21|  5241.392|
|eWeNd8sOKo+UyNyWB...|20151215|     2|     1|     0|      1|      4|      4|  1307.142|
|eWeNd8sOKo+UyNyWB...|20160407|     1|     0|     0|      1|      1|      3|   369.659|
|54SzDEGy4j04AoRxm...|20151205|     5|     1|     0|      2|     10|     17|  3261.387|
|54SzDEGy4j04AoRxm...|20160510|    12|     0|     2|      2|      2|     18|  1438.046|
|54SzDEGy4j04AoRxm...|20160917|     0|     1|     0|      0|     14|     15|   3338.81|
+--------------------+--------+------+------+------+-------+-------+-------+----------+
only showing top 20 rows

In [11]:
# function that fill convert the date from 20160607 format into datetime
def convert_date(x):
    x = str(x)
    date = datetime(year=int(x[0:4]), month=int(x[4:6]), day=int(x[6:8]))
    return date

In [12]:
from pyspark.sql.types import DateType
from pyspark.sql.functions import udf

In [13]:
udf_myFunction = udf(convert_date, DateType())

In [14]:
logs = logs.withColumn("date_timestamp", udf_myFunction("date"))

In [15]:
logs.show(20)

+--------------------+--------+------+------+------+-------+-------+-------+----------+--------------+
|                msno|    date|num_25|num_50|num_75|num_985|num_100|num_unq|total_secs|date_timestamp|
+--------------------+--------+------+------+------+-------+-------+-------+----------+--------------+
|L7Amv5Vawu+R52zRd...|20160612|     0|     1|     2|      0|      5|      6|  1438.998|    2016-06-12|
|L7Amv5Vawu+R52zRd...|20160805|     6|     0|     0|      1|     13|     16|  4014.902|    2016-08-05|
|L7Amv5Vawu+R52zRd...|20160926|     0|     0|     0|      1|     11|     12|   3642.45|    2016-09-26|
|L7Amv5Vawu+R52zRd...|20161123|     1|     0|     0|      2|     36|     22|   9738.31|    2016-11-23|
|L7Amv5Vawu+R52zRd...|20170114|     0|     0|     0|      1|     12|     12|  3176.986|    2017-01-14|
|6RDXC1K76TAc/Emo4...|20151106|     7|     1|     0|      3|     25|     34|  6497.174|    2015-11-06|
|6RDXC1K76TAc/Emo4...|20160110|     8|     0|     1|      0|     28|     34|  7434.636|    2016-01-10|
|6RDXC1K76TAc/Emo4...|20160411|     0|     0|     0|      0|      6|      6|  1689.972|    2016-04-11|
|6RDXC1K76TAc/Emo4...|20160621|     2|     3|     0|      0|      6|      9|  1826.677|    2016-06-21|
|6RDXC1K76TAc/Emo4...|20160925|     3|     0|     0|      0|      9|     12|  2303.381|    2016-09-25|
|6RDXC1K76TAc/Emo4...|20161123|     7|     4|     0|      0|      4|     15|  1528.046|    2016-11-23|
|xpNjjyiJvP16vv0XG...|20151201|     0|     0|     1|      0|      0|      1|   126.851|    2015-12-01|
|xpNjjyiJvP16vv0XG...|20160310|     1|     0|     2|      0|     19|     22|  5801.389|    2016-03-10|
|xpNjjyiJvP16vv0XG...|20160905|     0|     0|     0|      0|      2|      2|   542.406|    2016-09-05|
|xpNjjyiJvP16vv0XG...|20170214|     2|     1|     1|      0|     21|     21|  5241.392|    2017-02-14|
|eWeNd8sOKo+UyNyWB...|20151215|     2|     1|     0|      1|      4|      4|  1307.142|    2015-12-15|
|eWeNd8sOKo+UyNyWB...|20160407|     1|     0|     0|      1|      1|      3|   369.659|    2016-04-07|
|54SzDEGy4j04AoRxm...|20151205|     5|     1|     0|      2|     10|     17|  3261.387|    2015-12-05|
|54SzDEGy4j04AoRxm...|20160510|    12|     0|     2|      2|      2|     18|  1438.046|    2016-05-10|
|54SzDEGy4j04AoRxm...|20160917|     0|     1|     0|      0|     14|     15|   3338.81|    2016-09-17|
+--------------------+--------+------+------+------+-------+-------+-------+----------+--------------+
only showing top 20 rows

In [16]:
# group by month

In [17]:
from pyspark.sql.functions import month, mean, year

In [18]:
#logs_group = logs.groupBy(month("date_timestamp").alias("month")).agg(mean("value").alias("mean"))

In [19]:
#logs.groupBy(month("date_timestamp").alias("month")).agg(mean("total_secs").alias("mean")).show()

In [20]:
#logs.groupBy(month("date_timestamp").alias("month")).agg(mean(["num_25",
                                                               "num_50",
                                                               "num_75",
                                                               "num_985",
                                                               "num_100",
                                                               "num_unq",
                                                               "total_secs"]).alias(["num_25_mean",
                                                               "num_50_mean",
                                                               "num_75_mean",
                                                               "num_985_mean",
                                                               "num_100_mean",
                                                               "num_unq_mean",
                                                               "total_secs_mean"])).show()

IndentationError: unexpected indent (<ipython-input-20-e1f42ccc11fa>, line 2)

In [21]:
logs_group = logs.groupBy("msno", year("date_timestamp").alias("year"), month("date_timestamp").alias("month")).agg(
                                                        mean("num_25").alias("num_25_mean"),
                                                        mean("num_50").alias("num_50_mean"),
                                                        mean("num_75").alias("num_75_mean"),
                                                        mean("num_985").alias("num_985_mean"),
                                                        mean("num_100").alias("num_100_mean"),
                                                        mean("num_unq").alias("num_unq_mean"),
                                                        mean("total_secs").alias("total_secs_mean"),   
                                                        F.count("total_secs").alias("count")
                                                        )

In [22]:
from pyspark.sql.window import Window

In [23]:
logs_group.columns

['msno',
 'year',
 'month',
 'num_25_mean',
 'num_50_mean',
 'num_75_mean',
 'num_985_mean',
 'num_100_mean',
 'num_unq_mean',
 'total_secs_mean',
 'count']

In [24]:
logs_group.show()

+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+
|                msno|year|month|       num_25_mean|       num_50_mean|       num_75_mean|      num_985_mean|      num_100_mean|      num_unq_mean|   total_secs_mean|count|
+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+
|6RDXC1K76TAc/Emo4...|2016|    1|               6.5|               0.5|              1.25|              1.25|             47.75|              54.5|12520.911250000001|    4|
|ys1SnJX4y5EHzqbQM...|2016|    2|16.666666666666668|2.3333333333333335|1.3333333333333333|               3.0|15.666666666666666|              31.0|          4674.611|    3|
|1S2R5T4Ibzqf/UVcm...|2016|    4|               2.0|               0.0|               0.0|              0.25|               8.0|              8.75|         2199.5545|    4|
|zmm+FLTmXIjOQ0uF4...|2016|    4|              1.25|              1.25|               0.0|               0.5|              4.75|              7.25|        1411.67025|    4|
|LnHIVibim4ULMuQT2...|2016|    2|             11.25|               3.5|               3.5|               3.5|             27.75|              46.0|        8824.32125|    4|
|PCKNIZr8wx97NuLkK...|2016|   11|             16.75|               6.5|               4.0|               4.0|              31.0|              48.0|          8915.919|    4|
|lhP5Zlk0uBt7YHe78...|2016|    6|              4.25|              0.75|              0.75|              1.25|              10.0|             14.75|        3006.97225|    4|
|yHtqcNQKND3TJReQK...|2016|    5|3.6666666666666665|0.3333333333333333|0.3333333333333333|               1.0|3.6666666666666665| 4.666666666666667|1319.2513333333334|    3|
|ei+aYS164oxKrk5i7...|2016|    3|               1.5|               0.5|               0.0|               0.0|             15.25|             12.75|         3811.3305|    4|
|LmW3GaXPYBG+LvEnD...|2016|   12|3.3333333333333335|               2.0|               2.0|1.6666666666666667| 8.333333333333334|14.333333333333334| 2907.076333333333|    3|
|QfkguCJXkSWy7xcdN...|2016|    6|              1.75|               0.0|              0.25|               0.5|               7.5|              9.25|2137.7535000000003|    4|
|FnSjLSe8z5LRsTYJI...|2016|    5|              4.25|              1.25|              0.25|               0.5|              21.0|             21.75|         6114.7405|    4|
|V4Td6ya0696MrN/H0...|2016|   11|              2.25|              0.75|               0.5|              0.75|               7.0|             10.75|        2031.67875|    4|
|ZrQrsdFgYLenGgtbj...|2016|    5|              15.0|               7.0|               2.0|               0.0|               2.0|              17.0|          1823.631|    1|
|7TpaSFGW3UptOOjOv...|2017|    1|               4.5|              2.25|              1.25|               0.5|              14.0|             16.75|         3697.4455|    4|
|KJARqoEKtSF6t3PZG...|2016|   12|              23.5|              4.75|              3.75|               2.5|             28.75|             38.25|           8221.16|    4|
|c6rC99sCtTwrtJCLj...|2016|   12|               2.0|0.3333333333333333|1.6666666666666667|               1.0|              16.0|20.333333333333332|          4388.065|    3|
|+vCZptAnJ3xGCsqXu...|2016|    6|11.333333333333334|               4.0|2.6666666666666665|               1.0|               6.0| 9.666666666666666|2375.6803333333332|    3|
|zdsUImitbXYpf3Qsh...|2017|    1|              7.75|               0.5|              0.25|              0.75|              10.0|             13.75|         2705.8415|    4|
|GTP7du1NXA/k2XUOm...|2016|   11|               3.0|              3.25|              0.75|               0.0|             19.75|              22.5|           5165.59|    4|
+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+
only showing top 20 rows

In [25]:
wSpec = Window.partitionBy(logs_group["msno"]).orderBy(logs_group["year"],logs_group["month"]).rowsBetween(-3, 0)

In [26]:
for column in logs_group.columns[3:]:
    logs_group= logs_group.withColumn("movingAvg_"+ column, mean(column).over(wSpec))

In [27]:
logs_group.columns[3:]

['num_25_mean',
 'num_50_mean',
 'num_75_mean',
 'num_985_mean',
 'num_100_mean',
 'num_unq_mean',
 'total_secs_mean',
 'count',
 'movingAvg_num_25_mean',
 'movingAvg_num_50_mean',
 'movingAvg_num_75_mean',
 'movingAvg_num_985_mean',
 'movingAvg_num_100_mean',
 'movingAvg_num_unq_mean',
 'movingAvg_total_secs_mean',
 'movingAvg_count']

In [28]:
import pandas as pd

In [29]:
pd.DataFrame(logs_group.limit(50).collect(), columns = logs_group.columns)

,msno,year,month,num_25_mean,num_50_mean,num_75_mean,num_985_mean,num_100_mean,num_unq_mean,total_secs_mean,count,movingAvg_num_25_mean,movingAvg_num_50_mean,movingAvg_num_75_mean,movingAvg_num_985_mean,movingAvg_num_100_mean,movingAvg_num_unq_mean,movingAvg_total_secs_mean,movingAvg_count
0,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,2015,3,20.000000,1.666667,0.666667,2.000000,43.000000,55.000000,12523.194333,3,20.000000,1.666667,0.666667,2.000000,43.000000,55.000000,12523.194333,3.00
1,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,2015,6,6.333333,0.333333,0.333333,0.333333,27.000000,33.666667,7452.821667,3,13.166667,1.000000,0.500000,1.166667,35.000000,44.333333,9988.008000,3.00
2,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,2015,11,6.333333,0.333333,1.000000,1.333333,12.666667,20.333333,3996.003667,3,10.888889,0.777778,0.666667,1.222222,27.555556,36.333333,7990.673222,3.00
3,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,2016,3,5.000000,2.333333,1.333333,1.333333,1.000000,10.666667,978.806333,3,9.416667,1.166667,0.833333,1.250000,20.916667,29.916667,6237.706500,3.00
4,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,2016,5,7.666667,1.000000,1.333333,0.333333,6.666667,14.333333,1835.413667,3,6.333333,1.000000,1.000000,0.833333,11.833333,19.750000,3565.761333,3.00
5,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,2016,7,8.666667,1.000000,2.000000,0.666667,24.666667,34.666667,6776.827333,3,6.916667,1.166667,1.416667,0.916667,11.250000,20.000000,3396.762750,3.00
6,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,2016,9,8.333333,4.000000,2.000000,0.666667,15.000000,27.666667,4871.885333,3,7.416667,2.083333,1.666667,0.750000,11.833333,21.833333,3615.733167,3.00
7,++4RuqBw0Ss6bQU4oMxaRlbBPoWzoEiIZaxPM04Y4+U=,2016,11,2.333333,0.666667,0.000000,1.333333,4.333333,6.333333,1459.943667,3,6.750000,1.666667,1.333333,0.750000,12.666667,20.750000,3736.017500,3.00
8,++OepqRK4wiYg4Chl+qqo7TrwM+i9KZc3Ez/Swbjjew=,2016,1,2.250000,0.750000,0.500000,0.250000,59.250000,60.500000,15296.302750,4,2.250000,0.750000,0.500000,0.250000,59.250000,60.500000,15296.302750,4.00
9,++OepqRK4wiYg4Chl+qqo7TrwM+i9KZc3Ez/Swbjjew=,2016,3,2.000000,0.750000,1.750000,1.000000,16.000000,20.750000,4660.551500,4,2.125000,0.750000,1.125000,0.625000,37.625000,40.625000,9978.427125,4.00
10,+/namlXq+u3izRjHCFJV4MgqcXcLidZYszVsROOq/y4=,2016,10,2.000000,0.000000,0.000000,0.000000,4.000000,6.000000,1096.592000,1,2.000000,0.000000,0.000000,0.000000,4.000000,6.000000,1096.592000,1.00
11,+/namlXq+u3izRjHCFJV4MgqcXcLidZYszVsROOq/y4=,2016,11,26.000000,3.500000,2.000000,2.000000,44.500000,68.500000,12789.766000,2,14.000000,1.750000,1.000000,1.000000,24.250000,37.250000,6943.179000,1.50
12,+/namlXq+u3izRjHCFJV4MgqcXcLidZYszVsROOq/y4=,2017,1,17.333333,1.333333,2.000000,2.333333,34.333333,55.333333,9868.284333,3,15.111111,1.611111,1.333333,1.444444,27.611111,43.277778,7918.214111,2.00
13,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2015,2,0.000000,0.666667,0.333333,0.333333,28.000000,28.000000,7391.842000,3,0.000000,0.666667,0.333333,0.333333,28.000000,28.000000,7391.842000,3.00
14,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2015,5,1.666667,0.333333,0.333333,0.000000,20.333333,20.333333,5166.255667,3,0.833333,0.500000,0.333333,0.166667,24.166667,24.166667,6279.048833,3.00
15,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2015,7,4.000000,1.666667,0.666667,0.666667,12.000000,18.666667,3558.617000,3,1.888889,0.888889,0.444444,0.333333,20.111111,22.333333,5372.238222,3.00
16,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2015,9,0.666667,0.000000,0.000000,0.333333,43.666667,44.000000,10757.763667,3,1.583333,0.666667,0.333333,0.333333,26.000000,27.750000,6718.619583,3.00
17,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2015,11,2.000000,0.000000,0.000000,0.000000,21.000000,22.333333,5196.399667,3,2.083333,0.500000,0.250000,0.250000,24.250000,26.333333,6169.759000,3.00
18,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2016,1,5.333333,0.666667,0.333333,0.000000,14.000000,19.666667,3482.710000,3,3.000000,0.583333,0.250000,0.250000,22.666667,26.166667,5748.872583,3.00
19,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2016,3,7.000000,0.666667,0.333333,0.000000,18.666667,23.333333,4901.114667,3,3.750000,0.333333,0.166667,0.083333,24.333333,27.333333,6084.497000,3.00
20,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2016,4,3.333333,0.666667,0.333333,0.666667,20.666667,21.000000,5028.003000,3,4.416667,0.500000,0.250000,0.166667,18.583333,21.583333,4652.056833,3.00
21,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2016,6,8.000000,0.666667,1.000000,2.666667,42.333333,36.333333,11208.246333,3,5.916667,0.666667,0.500000,0.833333,23.916667,25.083333,6155.018500,3.00
22,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2016,8,3.000000,0.333333,0.333333,0.333333,19.000000,16.666667,4989.900333,3,5.333333,0.583333,0.500000,0.916667,25.166667,24.333333,6531.816083,3.00
23,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2016,10,4.333333,3.000000,2.000000,1.666667,75.333333,73.333333,20160.999667,3,4.666667,1.166667,0.916667,1.333333,39.333333,36.833333,10346.787333,3.00
24,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2016,12,3.666667,1.333333,0.333333,0.666667,24.000000,18.666667,5465.519333,3,4.750000,1.333333,0.916667,1.333333,40.166667,36.250000,10456.166417,3.00
25,+0/X9tkmyHyet9X80G6GTrDFHnJqvai8d1ZPhayT0os=,2017,2,23.666667,1.000000,2.000000,4.666667,88.000000,20.666667,21756.293667,3,8.666667,1.416667,1.166667,1.833333,51.583333,32.333333,13093.178250,3.00
26,+05qsxDhDDTpu2ToG9XjACu/xQbMqukeXDkQ8s1wN0M=,2015,4,14.333333,3.000000,1.333333,1.000000,20.333333,26.000000,6063.564000,3,14.333333,3.000000,1.333333,1.000000,20.333333,26.000000,6063.564000,3.00
27,+05qsxDhDDTpu2ToG9XjACu/xQbMqukeXDkQ8s1wN0M=,2015,7,8.333333,0.333333,1.333333,2.333333,35.000000,5.333333,5293.158000,3,11.333333,1.666667,1.333333,1.666667,27.666667,15.666667,5678.361000,3.00
28,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2015,2,1.666667,1.000000,2.000000,1.000000,51.000000,46.666667,13755.298000,3,1.666667,1.000000,2.000000,1.000000,51.000000,46.666667,13755.298000,3.00
29,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2015,4,1.666667,1.333333,0.000000,0.000000,63.000000,58.333333,16176.066333,3,1.666667,1.166667,1.000000,0.500000,57.000000,52.500000,14965.682167,3.00
30,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2015,6,0.000000,0.000000,0.000000,0.000000,53.000000,53.000000,12550.446333,3,1.111111,0.777778,0.666667,0.333333,55.666667,52.666667,14160.603556,3.00
31,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2015,7,0.000000,0.000000,0.000000,0.000000,95.000000,23.000000,26143.104000,1,0.833333,0.583333,0.500000,0.250000,65.500000,45.250000,17156.228667,2.50
32,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2015,8,6.000000,0.000000,1.000000,0.000000,46.500000,52.000000,11565.918500,2,1.916667,0.333333,0.250000,0.000000,64.375000,46.583333,16608.883792,2.25
33,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2015,10,3.666667,1.000000,1.000000,1.000000,68.333333,71.666667,16759.813333,3,2.416667,0.250000,0.500000,0.250000,65.708333,49.916667,16754.820542,2.25
34,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2015,12,6.000000,1.000000,0.333333,0.333333,19.333333,25.333333,4898.380333,3,3.916667,0.500000,0.583333,0.333333,57.291667,43.000000,14841.804042,2.25
35,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2016,3,1.666667,1.333333,1.000000,0.000000,29.333333,29.666667,7445.116000,3,4.333333,0.833333,0.833333,0.333333,40.875000,44.666667,10167.307042,2.75
36,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2016,5,5.333333,3.666667,0.000000,0.333333,68.000000,75.000000,17587.504333,3,4.166667,1.750000,0.583333,0.416667,46.250000,50.416667,11672.703500,3.00
37,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2016,7,2.333333,0.333333,0.000000,0.333333,98.333333,88.000000,25280.876667,3,3.833333,1.583333,0.333333,0.250000,53.750000,54.500000,13802.969333,3.00
38,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2016,8,3.000000,0.333333,0.333333,0.000000,17.666667,21.333333,4219.700333,3,3.083333,1.416667,0.333333,0.166667,53.333333,53.500000,13633.299333,3.00
39,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2016,10,3.333333,0.000000,0.000000,0.666667,5.333333,9.333333,1516.074000,3,3.500000,1.083333,0.083333,0.333333,47.333333,48.416667,12151.038833,3.00
40,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2016,12,10.666667,5.000000,5.000000,3.666667,24.666667,39.666667,8154.449667,3,4.833333,1.416667,1.333333,1.166667,36.500000,39.583333,9792.775167,3.00
41,+09YGn842g6h2EZUXe0VWeC4bBoCbDGfUboitc0vIHw=,2017,2,2.333333,0.333333,0.000000,0.333333,8.000000,11.000000,1999.946333,3,4.833333,1.416667,1.333333,1.166667,13.916667,20.333333,3972.542583,3.00
42,+0Q9TLFb5w470dEF62qlKTFF4f0os+tQiuRdklwvQ3o=,2015,2,11.000000,3.333333,0.666667,1.333333,51.666667,51.333333,13669.998667,3,11.000000,3.333333,0.666667,1.333333,51.666667,51.333333,13669.998667,3.00
43,+0Q9TLFb5w470dEF62qlKTFF4f0os+tQiuRdklwvQ3o=,2015,4,12.666667,2.000000,1.666667,2.333333,84.333333,81.333333,22245.363000,3,11.833333,2.666667,1.166667,1.833333,68.000000,66.333333,17957.680833,3.00
44,+0Q9TLFb5w470dEF62qlKTFF4f0os+tQiuRdklwvQ3o=,2015,6,17.000000,1.000000,1.666667,0.666667,18.666667,31.000000,5840.279000,3,13.555556,2.111111,1.333333,1.444444,51.555556,54.555556,13918.546889,3.00
45,+0Q9TLFb5w470dEF62qlKTFF4f0os+tQiuRdklwvQ3o=,2015,8,27.000000,2.666667,2.333333,2.333333,22.000000,46.666667,6790.116667,3,16.916667,2.250000,1.583333,1.666667,44.166667,52.583333,12136.439333,3.00
46,+0Q9TLFb5w470dEF62qlKTFF4f0os+tQiuRdklwvQ3o=,2015,10,5.333333,1.666667,0.666667,1.333333,82.333333,75.333333,21154.219667,3,15.500000,1.833333,1.583333,1.666667,51.833333,58.583333,14007.494583,3.00
47,+0RJtbyhoPAHPa+34MkYcE2Ox0cjMgJOTXMXVBYgkJE=,2015,3,2.500000,1.500000,3.000000,3.500000,14.750000,23.500000,5198.922750,4,2.500000,1.500000,3.000000,3.500000,14.750000,23.500000,5198.922750,4.00
48,+0RJtbyhoPAHPa+34MkYcE2Ox0cjMgJOTXMXVBYgkJE=,2015,6,4.000000,1.250000,1.250000,1.750000,26.500000,26.000000,7507.959500,4,3.250000,1.375000,2.125000,2.625000,20.625000,24.750000,6353.441125,4.00
49,+0RJtbyhoPAHPa+34MkYcE2Ox0cjMgJOTXMXVBYgkJE=,2015,9,0.000000,0.000000,0.250000,0.250000,20.000000,18.500000,4846.717750,4,2.166667,0.916667,1.500000,1.833333,20.416667,22.666667,5851.200000,4.00

In [70]:
from pyspark.sql.functions import rank, col

In [69]:
window = Window.partitionBy(df['user_id']).orderBy(df['score'].desc())

df.select('*', rank().over(window).alias('rank')) 
  .filter(col('rank') <= 2) 
  .show()

AttributeError: 'GroupedData' object has no attribute 'tail'

In [71]:
window = Window.partitionBy(logs_group['msno']).orderBy(logs_group['year'].desc(), logs_group['month'].desc())

In [76]:
logs_group_last3 = logs_group.select('*', rank().over(window).alias('rank'))\
    .filter(col('rank') <= 3)\

In [77]:
logs_group_last3.show()

+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+---------------------+---------------------+---------------------+----------------------+----------------------+----------------------+-------------------------+---------------+----+
|                msno|year|month|       num_25_mean|       num_50_mean|       num_75_mean|      num_985_mean|      num_100_mean|      num_unq_mean|   total_secs_mean|count|movingAvg_num_25_mean|movingAvg_num_50_mean|movingAvg_num_75_mean|movingAvg_num_985_mean|movingAvg_num_100_mean|movingAvg_num_unq_mean|movingAvg_total_secs_mean|movingAvg_count|rank|
+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+---------------------+---------------------+---------------------+----------------------+----------------------+----------------------+-------------------------+---------------+----+
|++4RuqBw0Ss6bQU4o...|2016|   11|2.3333333333333335|0.6666666666666666|               0.0|1.3333333333333333| 4.333333333333333| 6.333333333333333|1459.9436666666663|    3|    6.749999999999999|   1.6666666666666667|   1.3333333333333333|                  0.75|    12.666666666666668|                 20.75|                3736.0175|            3.0|   1|
|++4RuqBw0Ss6bQU4o...|2016|    9| 8.333333333333334|               4.0|               2.0|0.6666666666666666|              15.0|27.666666666666668| 4871.885333333333|    3|    7.416666666666668|   2.0833333333333335|   1.6666666666666665|    0.7499999999999999|    11.833333333333334|    21.833333333333332|        3615.733166666667|            3.0|   2|
|++4RuqBw0Ss6bQU4o...|2016|    7| 8.666666666666666|               1.0|               2.0|0.6666666666666666|24.666666666666668|34.666666666666664| 6776.827333333334|    3|    6.916666666666666|   1.1666666666666667|   1.4166666666666665|    0.9166666666666666|                 11.25|                  20.0|               3396.76275|            3.0|   3|
|++OepqRK4wiYg4Chl...|2016|    3|               2.0|              0.75|              1.75|               1.0|              16.0|             20.75|4660.5515000000005|    4|                2.125|                 0.75|                1.125|                 0.625|                37.625|                40.625|              9978.427125|            4.0|   1|
|++OepqRK4wiYg4Chl...|2016|    1|              2.25|              0.75|               0.5|              0.25|             59.25|              60.5|15296.302749999999|    4|                 2.25|                 0.75|                  0.5|                  0.25|                 59.25|                  60.5|       15296.302749999999|            4.0|   2|
|+/namlXq+u3izRjHC...|2017|    1|17.333333333333332|1.3333333333333333|               2.0|2.3333333333333335|34.333333333333336|55.333333333333336| 9868.284333333333|    3|   15.111111111111109|    1.611111111111111|   1.3333333333333333|    1.4444444444444446|    27.611111111111114|     43.27777777777778|        7918.214111111111|            2.0|   1|
|+/namlXq+u3izRjHC...|2016|   11|              26.0|               3.5|               2.0|               2.0|              44.5|              68.5|         12789.766|    2|                 14.0|                 1.75|                  1.0|                   1.0|                 24.25|                 37.25|                 6943.179|            1.5|   2|
|+/namlXq+u3izRjHC...|2016|   10|               2.0|               0.0|               0.0|               0.0|               4.0|               6.0|          1096.592|    1|                  2.0|                  0.0|                  0.0|                   0.0|                   4.0|                   6.0|                 1096.592|            1.0|   3|
|+0/X9tkmyHyet9X80...|2017|    2|23.666666666666668|               1.0|               2.0| 4.666666666666667|              88.0|20.666666666666668| 21756.29366666667|    3|    8.666666666666668|   1.4166666666666667|   1.1666666666666667|    1.8333333333333335|     51.58333333333333|    32.333333333333336|              13093.17825|            3.0|   1|
|+0/X9tkmyHyet9X80...|2016|   12|3.6666666666666665|1.3333333333333333|0.3333333333333333|0.6666666666666666|              24.0|18.666666666666668| 5465.519333333333|    3|                 4.75|   1.3333333333333333|   0.9166666666666666|    1.3333333333333335|    40.166666666666664|                 36.25|       10456.166416666667|            3.0|   2|
|+0/X9tkmyHyet9X80...|2016|   10| 4.333333333333333|               3.0|               2.0|1.6666666666666667| 75.33333333333333| 73.33333333333333|20160.999666666667|    3|    4.666666666666667|   1.1666666666666665|   0.9166666666666666|    1.3333333333333333|     39.33333333333333|     36.83333333333333|       10346.787333333334|            3.0|   3|
|+05qsxDhDDTpu2ToG...|2015|    7| 8.333333333333334|0.3333333333333333|1.3333333333333333|2.3333333333333335|              35.0| 5.333333333333333|          5293.158|    3|   11.333333333333334|   1.6666666666666667|   1.3333333333333333|    1.6666666666666667|    27.666666666666664|    15.666666666666666|        5678.361000000001|            3.0|   1|
|+05qsxDhDDTpu2ToG...|2015|    4|14.333333333333334|               3.0|1.3333333333333333|               1.0|20.333333333333332|              26.0| 6063.564000000001|    3|   14.333333333333334|                  3.0|   1.3333333333333333|                   1.0|    20.333333333333332|                  26.0|        6063.564000000001|            3.0|   2|
|+09YGn842g6h2EZUX...|2017|    2|2.3333333333333335|0.3333333333333333|               0.0|0.3333333333333333|               8.0|              11.0|1999.9463333333333|    3|    4.833333333333333|   1.4166666666666665|   1.3333333333333333|    1.1666666666666665|    13.916666666666668|    20.333333333333332|       3972.5425833333334|            3.0|   1|
|+09YGn842g6h2EZUX...|2016|   12|10.666666666666666|               5.0|               5.0|3.6666666666666665|24.666666666666668|39.666666666666664| 8154.449666666667|    3|    4.833333333333334|   1.4166666666666667|   1.3333333333333333|    1.1666666666666665|                  36.5|     39.58333333333333|        9792.775166666666|            3.0|   2|
|+09YGn842g6h2EZUX...|2016|   10|3.3333333333333335|               0.0|               0.0|0.6666666666666666| 5.333333333333333| 9.333333333333334|1516.0739999999998|    3|                  3.5|   1.0833333333333333|  0.08333333333333333|    0.3333333333333333|     47.33333333333333|     48.41666666666667|       12151.038833333334|            3.0|   3|
|+0Q9TLFb5w470dEF6...|2015|   10| 5.333333333333333|1.6666666666666667|0.6666666666666666|1.3333333333333333| 82.33333333333333| 75.33333333333333|21154.219666666668|    3|                 15.5|   1.8333333333333333|   1.5833333333333335|    1.6666666666666667|     51.83333333333333|     58.58333333333333|       14007.494583333333|            3.0|   1|
|+0Q9TLFb5w470dEF6...|2015|    8|              27.0|2.6666666666666665|2.3333333333333335|2.3333333333333335|              22.0|46.666666666666664| 6790.116666666666|    3|   16.916666666666664|                 2.25|   1.5833333333333335|     1.666666666666667|    44.166666666666664|     52.58333333333333|       12136.439333333334|            3.0|   2|
|+0Q9TLFb5w470dEF6...|2015|    6|              17.0|               1.0|1.6666666666666667|0.6666666666666666|18.666666666666668|              31.0|5840.2789999999995|    3|   13.555555555555555|    2.111111111111111|   1.3333333333333333|    1.4444444444444446|     51.55555555555555|     54.55555555555555|       13918.546888888888|            3.0|   3|
|+0RJtbyhoPAHPa+34...|2017|    2|              3.25|              0.75|              1.25|               2.5|              15.0|             21.25| 4437.666749999999|    4|                3.875|                  1.0|                 0.75|                1.1875|                  24.0|               28.8125|             6328.5070625|            4.0|   1|
+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+---------------------+---------------------+---------------------+----------------------+----------------------+----------------------+-------------------------+---------------+----+
only showing top 20 rows

In [80]:
logs_group_last3.columns[3:-1]

['num_25_mean',
 'num_50_mean',
 'num_75_mean',
 'num_985_mean',
 'num_100_mean',
 'num_unq_mean',
 'total_secs_mean',
 'count',
 'movingAvg_num_25_mean',
 'movingAvg_num_50_mean',
 'movingAvg_num_75_mean',
 'movingAvg_num_985_mean',
 'movingAvg_num_100_mean',
 'movingAvg_num_unq_mean',
 'movingAvg_total_secs_mean',
 'movingAvg_count']

In [81]:
col_list = ['movingAvg_num_25_mean',
 'movingAvg_num_50_mean',
 'movingAvg_num_75_mean',
 'movingAvg_num_985_mean',
 'movingAvg_num_100_mean',
 'movingAvg_num_unq_mean',
 'movingAvg_total_secs_mean',
 'movingAvg_count']

In [ ]:
window = Window.partitionBy(logs_group['msno']).orderBy(logs_group['year'].desc(), logs_group['month'].desc())

In [83]:
window2=Window.partitionBy(logs_group_last3['msno']).orderBy(logs_group_last3['year'], logs_group_last3['month'])

In [85]:
for column in col_list: 
    logs_group_last3 = logs_group_last3.withColumn("lag_" + column, F.lag(column, 1).over(window2))

In [ ]:
logs_group_last3

In [91]:
logs_group_last3 = logs_group_last3.filter(col("lag_movingAvg_num_25_mean").isNotNull())

In [93]:
logs_group_last3.columns

['msno',
 'year',
 'month',
 'num_25_mean',
 'num_50_mean',
 'num_75_mean',
 'num_985_mean',
 'num_100_mean',
 'num_unq_mean',
 'total_secs_mean',
 'count',
 'movingAvg_num_25_mean',
 'movingAvg_num_50_mean',
 'movingAvg_num_75_mean',
 'movingAvg_num_985_mean',
 'movingAvg_num_100_mean',
 'movingAvg_num_unq_mean',
 'movingAvg_total_secs_mean',
 'movingAvg_count',
 'rank',
 'lag_movingAvg_num_25_mean',
 'lag_movingAvg_num_50_mean',
 'lag_movingAvg_num_75_mean',
 'lag_movingAvg_num_985_mean',
 'lag_movingAvg_num_100_mean',
 'lag_movingAvg_num_unq_mean',
 'lag_movingAvg_total_secs_mean',
 'lag_movingAvg_count']

In [95]:
col_list2 = [
    'num_25_mean',
 'num_50_mean',
 'num_75_mean',
 'num_985_mean',
 'num_100_mean',
 'num_unq_mean',
 'total_secs_mean',
 'count'   
]

In [101]:
logs_group_last3.columns

['msno',
 'year',
 'month',
 'num_25_mean',
 'num_50_mean',
 'num_75_mean',
 'num_985_mean',
 'num_100_mean',
 'num_unq_mean',
 'total_secs_mean',
 'count',
 'movingAvg_num_25_mean',
 'movingAvg_num_50_mean',
 'movingAvg_num_75_mean',
 'movingAvg_num_985_mean',
 'movingAvg_num_100_mean',
 'movingAvg_num_unq_mean',
 'movingAvg_total_secs_mean',
 'movingAvg_count',
 'rank',
 'lag_movingAvg_num_25_mean',
 'lag_movingAvg_num_50_mean',
 'lag_movingAvg_num_75_mean',
 'lag_movingAvg_num_985_mean',
 'lag_movingAvg_num_100_mean',
 'lag_movingAvg_num_unq_mean',
 'lag_movingAvg_total_secs_mean',
 'lag_movingAvg_count',
 'rank']

In [108]:
value_columns = ['lag_movingAvg_num_25_mean',
 'lag_movingAvg_num_50_mean',
 'lag_movingAvg_num_75_mean',
 'lag_movingAvg_num_985_mean',
 'lag_movingAvg_num_100_mean',
 'lag_movingAvg_num_unq_mean',
 'lag_movingAvg_total_secs_mean',
 'lag_movingAvg_count','count']

In [96]:
for column in col_list2:
    logs_group_last3.withColumn("div_" + column, col(column)/ col("lag_movingAvg_"+ column) )

In [99]:
window = Window.partitionBy(logs_group_last3['msno']).orderBy(logs_group_last3['year'], logs_group_last3['month'])

In [104]:
logs_group_last3 = logs_group_last3.select('*', rank().over(window).alias('rank2'))

In [106]:
logs_group_last3_piv = logs_group_last3.groupBy(col('msno')).pivot("rank2").sum(value_column)

Py4JJavaError: An error occurred while calling o987.sum.
: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at org.apache.spark.sql.RelationalGroupedDataset$$anonfun$3.apply(RelationalGroupedDataset.scala:98)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.RelationalGroupedDataset.aggregateNumericColumns(RelationalGroupedDataset.scala:98)
	at org.apache.spark.sql.RelationalGroupedDataset.sum(RelationalGroupedDataset.scala:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

In [110]:
logs_group_last3.columns

['msno',
 'year',
 'month',
 'num_25_mean',
 'num_50_mean',
 'num_75_mean',
 'num_985_mean',
 'num_100_mean',
 'num_unq_mean',
 'total_secs_mean',
 'count',
 'movingAvg_num_25_mean',
 'movingAvg_num_50_mean',
 'movingAvg_num_75_mean',
 'movingAvg_num_985_mean',
 'movingAvg_num_100_mean',
 'movingAvg_num_unq_mean',
 'movingAvg_total_secs_mean',
 'movingAvg_count',
 'rank',
 'lag_movingAvg_num_25_mean',
 'lag_movingAvg_num_50_mean',
 'lag_movingAvg_num_75_mean',
 'lag_movingAvg_num_985_mean',
 'lag_movingAvg_num_100_mean',
 'lag_movingAvg_num_unq_mean',
 'lag_movingAvg_total_secs_mean',
 'lag_movingAvg_count',
 'rank',
 'rank2']

In [112]:
logs_group_last3.groupBy(col('msno')).count().show()

+--------------------+-----+
|                msno|count|
+--------------------+-----+
|++4RuqBw0Ss6bQU4o...|    2|
|++OepqRK4wiYg4Chl...|    1|
|+/namlXq+u3izRjHC...|    2|
|+0/X9tkmyHyet9X80...|    2|
|+05qsxDhDDTpu2ToG...|    1|
|+09YGn842g6h2EZUX...|    2|
|+0Q9TLFb5w470dEF6...|    2|
|+0RJtbyhoPAHPa+34...|    2|
|+0jTOa6KGPk1vtNTw...|    2|
|+0l+FDuhyjaZnu0AP...|    2|
|+0l/WkoOIugT69NYa...|    2|
|+2Df04hr61UUJijMM...|    2|
|+2KZws+cYLzerLNA6...|    2|
|+2eLsQv6T46iKwO+m...|    2|
|+2oK/qWmYvAnfNZsV...|    2|
|+2sYXqnHWBACTG4Py...|    2|
|+2vC1rM36Emx77Uan...|    2|
|+43UqHvqzu5STDVIu...|    2|
|+4XdQOd2lqwKAzUkL...|    2|
|+50G1jyzn4OzqalwB...|    2|
+--------------------+-----+
only showing top 20 rows

In [119]:
pivot_first = logs_group_last3.groupBy(col('msno')).pivot("rank2").agg(mean(col("lag_movingAvg_num_25_mean")))

In [123]:
pivot_first = pivot_first.withColumnRenamed("1", "lag_movingAvg_num_25_mean_1").withColumnRenamed("2", "lag_movingAvg_num_25_mean_2")

In [124]:
column_list3 = [ 
'lag_movingAvg_num_50_mean',
 'lag_movingAvg_num_75_mean',
 'lag_movingAvg_num_985_mean',
 'lag_movingAvg_num_100_mean',
 'lag_movingAvg_num_unq_mean',
 'lag_movingAvg_total_secs_mean',
 'lag_movingAvg_count'
]

In [128]:
pivot_transit.columns

['msno', 'lag_movingAvg_num_50_mean_1', 'lag_movingAvg_num_50_mean_2']

In [129]:
for column in column_list3:
    pivot_transit = logs_group_last3.groupBy(col('msno')).pivot("rank2").agg(mean(col(column)))
    pivot_transit = pivot_transit.withColumnRenamed("1", column +"_1").withColumnRenamed("2", column +"_2")
    pivot_first = pivot_first.join(pivot_transit, "msno", "inner")

In [130]:
pivot_first.columns

['msno',
 'lag_movingAvg_num_25_mean_1',
 'lag_movingAvg_num_25_mean_2',
 'lag_movingAvg_num_50_mean_1',
 'lag_movingAvg_num_50_mean_2',
 'lag_movingAvg_num_75_mean_1',
 'lag_movingAvg_num_75_mean_2',
 'lag_movingAvg_num_985_mean_1',
 'lag_movingAvg_num_985_mean_2',
 'lag_movingAvg_num_100_mean_1',
 'lag_movingAvg_num_100_mean_2',
 'lag_movingAvg_num_unq_mean_1',
 'lag_movingAvg_num_unq_mean_2',
 'lag_movingAvg_total_secs_mean_1',
 'lag_movingAvg_total_secs_mean_2',
 'lag_movingAvg_count_1',
 'lag_movingAvg_count_2']

In [131]:
pivot_first.write.parquet("/media/andraa/10160545101605452/kaggle/WSDM-kaggle/data/pivot_first")

Py4JJavaError: An error occurred while calling o1266.parquet.
: org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply$mcV$sp(FileFormatWriter.scala:215)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:173)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:145)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.datasources.DataSource.writeInFileFormat(DataSource.scala:438)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:474)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)
	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:509)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 310.0 failed 1 times, most recent failure: Lost task 2.0 in stage 310.0 (TID 18300, localhost, executor driver): java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at org.apache.spark.sql.execution.python.DiskRowQueue.add(RowQueue.scala:125)
	at org.apache.spark.sql.execution.python.HybridRowQueue.add(RowQueue.scala:242)
	at org.apache.spark.sql.execution.python.BatchEvalPythonExec$$anonfun$doExecute$1$$anonfun$6.apply(BatchEvalPythonExec.scala:123)
	at org.apache.spark.sql.execution.python.BatchEvalPythonExec$$anonfun$doExecute$1$$anonfun$6.apply(BatchEvalPythonExec.scala:122)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:1076)
	at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:1091)
	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1129)
	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1132)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:509)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:333)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply$mcV$sp(FileFormatWriter.scala:188)
	... 45 more
Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at org.apache.spark.sql.execution.python.DiskRowQueue.add(RowQueue.scala:125)
	at org.apache.spark.sql.execution.python.HybridRowQueue.add(RowQueue.scala:242)
	at org.apache.spark.sql.execution.python.BatchEvalPythonExec$$anonfun$doExecute$1$$anonfun$6.apply(BatchEvalPythonExec.scala:123)
	at org.apache.spark.sql.execution.python.BatchEvalPythonExec$$anonfun$doExecute$1$$anonfun$6.apply(BatchEvalPythonExec.scala:122)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:1076)
	at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:1091)
	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1129)
	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1132)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:509)
	at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:333)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1954)
	at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:269)

In [120]:
pivot_first.show()

+--------------------+------------------+------------------+
|                msno|                 1|                 2|
+--------------------+------------------+------------------+
|++4RuqBw0Ss6bQU4o...| 6.916666666666666| 7.416666666666668|
|++OepqRK4wiYg4Chl...|              2.25|              null|
|+/namlXq+u3izRjHC...|               2.0|              14.0|
|+0/X9tkmyHyet9X80...| 4.666666666666667|              4.75|
|+05qsxDhDDTpu2ToG...|14.333333333333334|              null|
|+09YGn842g6h2EZUX...|               3.5| 4.833333333333334|
|+0Q9TLFb5w470dEF6...|13.555555555555555|16.916666666666664|
|+0RJtbyhoPAHPa+34...|            2.6875|            3.5625|
|+0jTOa6KGPk1vtNTw...| 7.250000000000001| 6.583333333333334|
|+0l+FDuhyjaZnu0AP...|               4.0|              4.75|
|+0l/WkoOIugT69NYa...|2.0833333333333335| 2.083333333333333|
|+2Df04hr61UUJijMM...|               3.0| 3.333333333333333|
|+2KZws+cYLzerLNA6...|              4.25|            3.5625|
|+2eLsQv6T46iKwO+m...|            6.9375|            4.6875|
|+2oK/qWmYvAnfNZsV...|18.416666666666668|17.416666666666668|
|+2sYXqnHWBACTG4Py...|3.5833333333333335| 2.388888888888889|
|+2vC1rM36Emx77Uan...|              19.5|           20.0625|
|+43UqHvqzu5STDVIu...|              0.75|            0.8125|
|+4XdQOd2lqwKAzUkL...|0.3333333333333333| 2.833333333333333|
|+50G1jyzn4OzqalwB...|               3.0|               5.5|
+--------------------+------------------+------------------+
only showing top 20 rows

In [ ]:
logs_group_last3.groupBy(col('msno')).pivot("rank2").mean("lag_movingAvg_num_25_mean")).show()

In [111]:
logs_group_last3.groupBy(col('msno')).pivot("rank2").sum(col("lag_movingAvg_num_25_mean")).show()

TypeError: Column is not iterable

In [ ]:
logs_group_last3.withColumn("lag_movingAvg_num_25_mean", "movingAvg_num_25_mean")

In [78]:
pd.DataFrame(logs_group_last3.limit(50).collect(), columns = logs_group.columns)

AssertionError: 19 columns passed, passed data had 20 columns

In [55]:
logs_group.show()

+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+--------------+------------------+-----------------+---------------------+---------------------+---------------------+----------------------+----------------------+----------------------+-------------------------+---------------+
|                msno|year|month|       num_25_mean|       num_50_mean|       num_75_mean|      num_985_mean|      num_100_mean|      num_unq_mean|   total_secs_mean|count|movingAvg_msno|    movingAvg_year|  movingAvg_month|movingAvg_num_25_mean|movingAvg_num_50_mean|movingAvg_num_75_mean|movingAvg_num_985_mean|movingAvg_num_100_mean|movingAvg_num_unq_mean|movingAvg_total_secs_mean|movingAvg_count|
+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+--------------+------------------+-----------------+---------------------+---------------------+---------------------+----------------------+----------------------+----------------------+-------------------------+---------------+
|++4RuqBw0Ss6bQU4o...|2015|    3|              20.0|1.6666666666666667|0.6666666666666666|               2.0|              43.0|              55.0|12523.194333333333|    3|          null|            2015.0|              3.0|                 20.0|   1.6666666666666667|   0.6666666666666666|                   2.0|                  43.0|                  55.0|       12523.194333333333|            3.0|
|++4RuqBw0Ss6bQU4o...|2015|    6| 6.333333333333333|0.3333333333333333|0.3333333333333333|0.3333333333333333|              27.0|33.666666666666664| 7452.821666666667|    3|          null|            2015.0|              4.5|   13.166666666666666|                  1.0|                  0.5|    1.1666666666666667|                  35.0|     44.33333333333333|                 9988.008|            3.0|
|++4RuqBw0Ss6bQU4o...|2015|   11| 6.333333333333333|0.3333333333333333|               1.0|1.3333333333333333|12.666666666666666|20.333333333333332| 3996.003666666666|    3|          null|            2015.0|6.666666666666667|   10.888888888888888|   0.7777777777777778|   0.6666666666666666|    1.2222222222222223|    27.555555555555557|     36.33333333333333|        7990.673222222223|            3.0|
|++4RuqBw0Ss6bQU4o...|2016|    3|               5.0|2.3333333333333335|1.3333333333333333|1.3333333333333333|               1.0|10.666666666666666| 978.8063333333333|    3|          null|           2015.25|             5.75|    9.416666666666666|   1.1666666666666667|   0.8333333333333333|                  1.25|    20.916666666666668|    29.916666666666664|                6237.7065|            3.0|
|++4RuqBw0Ss6bQU4o...|2016|    5| 7.666666666666667|               1.0|1.3333333333333333|0.3333333333333333| 6.666666666666667|14.333333333333334|1835.4136666666666|    3|          null|            2015.5|             6.25|    6.333333333333333|                  1.0|                  1.0|    0.8333333333333334|    11.833333333333332|                 19.75|       3565.7613333333334|            3.0|
|++4RuqBw0Ss6bQU4o...|2016|    7| 8.666666666666666|               1.0|               2.0|0.6666666666666666|24.666666666666668|34.666666666666664| 6776.827333333334|    3|          null|           2015.75|              6.5|    6.916666666666666|   1.1666666666666667|   1.4166666666666665|    0.9166666666666666|                 11.25|                  20.0|               3396.76275|            3.0|
|++4RuqBw0Ss6bQU4o...|2016|    9| 8.333333333333334|               4.0|               2.0|0.6666666666666666|              15.0|27.666666666666668| 4871.885333333333|    3|          null|            2016.0|              6.0|    7.416666666666668|   2.0833333333333335|   1.6666666666666665|    0.7499999999999999|    11.833333333333334|    21.833333333333332|        3615.733166666667|            3.0|
|++4RuqBw0Ss6bQU4o...|2016|   11|2.3333333333333335|0.6666666666666666|               0.0|1.3333333333333333| 4.333333333333333| 6.333333333333333|1459.9436666666663|    3|          null|            2016.0|              8.0|    6.749999999999999|   1.6666666666666667|   1.3333333333333333|                  0.75|    12.666666666666668|                 20.75|                3736.0175|            3.0|
|++OepqRK4wiYg4Chl...|2016|    1|              2.25|              0.75|               0.5|              0.25|             59.25|              60.5|15296.302749999999|    4|          null|            2016.0|              1.0|                 2.25|                 0.75|                  0.5|                  0.25|                 59.25|                  60.5|       15296.302749999999|            4.0|
|++OepqRK4wiYg4Chl...|2016|    3|               2.0|              0.75|              1.75|               1.0|              16.0|             20.75|4660.5515000000005|    4|          null|            2016.0|              2.0|                2.125|                 0.75|                1.125|                 0.625|                37.625|                40.625|              9978.427125|            4.0|
|+/namlXq+u3izRjHC...|2016|   10|               2.0|               0.0|               0.0|               0.0|               4.0|               6.0|          1096.592|    1|          null|            2016.0|             10.0|                  2.0|                  0.0|                  0.0|                   0.0|                   4.0|                   6.0|                 1096.592|            1.0|
|+/namlXq+u3izRjHC...|2016|   11|              26.0|               3.5|               2.0|               2.0|              44.5|              68.5|         12789.766|    2|          null|            2016.0|             10.5|                 14.0|                 1.75|                  1.0|                   1.0|                 24.25|                 37.25|                 6943.179|            1.5|
|+/namlXq+u3izRjHC...|2017|    1|17.333333333333332|1.3333333333333333|               2.0|2.3333333333333335|34.333333333333336|55.333333333333336| 9868.284333333333|    3|          null|2016.3333333333333|7.333333333333333|   15.111111111111109|    1.611111111111111|   1.3333333333333333|    1.4444444444444446|    27.611111111111114|     43.27777777777778|        7918.214111111111|            2.0|
|+0/X9tkmyHyet9X80...|2015|    2|               0.0|0.6666666666666666|0.3333333333333333|0.3333333333333333|              28.0|              28.0| 7391.842000000001|    3|          null|            2015.0|              2.0|                  0.0|   0.6666666666666666|   0.3333333333333333|    0.3333333333333333|                  28.0|                  28.0|        7391.842000000001|            3.0|
|+0/X9tkmyHyet9X80...|2015|    5|1.6666666666666667|0.3333333333333333|0.3333333333333333|               0.0|20.333333333333332|20.333333333333332| 5166.255666666667|    3|          null|            2015.0|              3.5|   0.8333333333333334|                  0.5|   0.3333333333333333|   0.16666666666666666|    24.166666666666664|    24.166666666666664|        6279.048833333334|            3.0|
|+0/X9tkmyHyet9X80...|2015|    7|               4.0|1.6666666666666667|0.6666666666666666|0.6666666666666666|              12.0|18.666666666666668|3558.6169999999997|    3|          null|            2015.0|4.666666666666667|    1.888888888888889|    0.888888888888889|   0.4444444444444444|    0.3333333333333333|     20.11111111111111|    22.333333333333332|        5372.238222222223|            3.0|
|+0/X9tkmyHyet9X80...|2015|    9|0.6666666666666666|               0.0|               0.0|0.3333333333333333|43.666666666666664|              44.0|10757.763666666666|    3|          null|            2015.0|             5.75|   1.5833333333333335|   0.6666666666666667|   0.3333333333333333|    0.3333333333333333|                  26.0|                 27.75|        6718.619583333333|            3.0|
|+0/X9tkmyHyet9X80...|2015|   11|               2.0|               0.0|               0.0|               0.0|              21.0|22.333333333333332| 5196.399666666667|    3|          null|            2015.0|              8.0|   2.0833333333333335|                  0.5|                 0.25|                  0.25|                 24.25|    26.333333333333332|                 6169.759|            3.0|
|+0/X9tkmyHyet9X80...|2016|    1| 5.333333333333333|0.6666666666666666|0.3333333333333333|               0.0|              14.0|19.666666666666668|3482.7099999999996|    3|          null|           2015.25|              7.0|                  3.0|   0.5833333333333334|                 0.25|                  0.25|    22.666666666666664|    26.166666666666668|        5748.872583333333|            3.0|
|+0/X9tkmyHyet9X80...|2016|    3|               7.0|0.6666666666666666|0.3333333333333333|               0.0|18.666666666666668|23.333333333333332| 4901.114666666666|    3|          null|            2015.5|              6.0|                 3.75|   0.3333333333333333|  0.16666666666666666|   0.08333333333333333|    24.333333333333332|    27.333333333333332|        6084.496999999999|            3.0|
+--------------------+----+-----+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-----+--------------+------------------+-----------------+---------------------+---------------------+---------------------+----------------------+----------------------+----------------------+-------------------------+---------------+
only showing top 20 rows

In [ ]:
logs_group.withColumn( “movingAvg”, avg(customers(“amountSpent”)).over(wSpec1)  ).show()

In [ ]:
customers.withColumn( “movingAvg”, avg(customers(“amountSpent”)).over(wSpec1)  ).show()

In [ ]:
df.select(col("*"), mean("some_value").over(w).alias("mean")).show()

In [12]:
# In the following session we want to obtain the logs just for the users that interest us
#########################################################################################

# read the test and the training 
train_msno = (sqlCtx
      .read.format('com.databricks.spark.csv')
      .options(header='true', inferschema='true')
      .load("/media/andraa/10160545101605452/kaggle/WSDM-kaggle/data/train.csv"))

test_msno = (sqlCtx
      .read.format('com.databricks.spark.csv')
      .options(header='true', inferschema='true')
      .load("/media/andraa/10160545101605452/kaggle/WSDM-kaggle/data/sample_submission_zero.csv"))

In [25]:
train_msno.show(5)

+--------------------+--------+
|                msno|is_churn|
+--------------------+--------+
|waLDQMmcOu2jLDaV1...|       1|
|QA7uiXy8vIbUSPOkC...|       1|
|fGwBva6hikQmTJzrb...|       1|
|mT5V8rEpa+8wuqi6x...|       1|
|XaPhtGLk/5UvvOYHc...|       1|
+--------------------+--------+
only showing top 5 rows

In [26]:
test_msno.show(5)

+--------------------+--------+
|                msno|is_churn|
+--------------------+--------+
|ugx0CjOMzazClkFzU...|       0|
|f/NmvEzHfhINFEYZT...|       0|
|zLo9f73nGGT1p21lt...|       0|
|8iF/+8HY8lJKFrTc7...|       0|
|K6fja4+jmoZ5xG6By...|       0|
+--------------------+--------+
only showing top 5 rows

In [13]:
# keep only the msno columns
from functools import reduce
train_msno = reduce(DataFrame.drop, ['is_churn'], train_msno)
train_msno.show(5)
test_msno = reduce(DataFrame.drop, ['is_churn'], test_msno)

+--------------------+
|                msno|
+--------------------+
|waLDQMmcOu2jLDaV1...|
|QA7uiXy8vIbUSPOkC...|
|fGwBva6hikQmTJzrb...|
|mT5V8rEpa+8wuqi6x...|
|XaPhtGLk/5UvvOYHc...|
+--------------------+
only showing top 5 rows

In [14]:
# do a merge with the logs dataframe
train_test_msno = train_msno.unionAll(test_msno)

In [15]:
train_test_msno.show(5)

+--------------------+
|                msno|
+--------------------+
|waLDQMmcOu2jLDaV1...|
|QA7uiXy8vIbUSPOkC...|
|fGwBva6hikQmTJzrb...|
|mT5V8rEpa+8wuqi6x...|
|XaPhtGLk/5UvvOYHc...|
+--------------------+
only showing top 5 rows

In [16]:
from pyspark.sql.functions import *

In [25]:
# merge the user logs and the train_test msno
logs_train_test = logs.join(train_test_msno, logs.msno == train_test_msno.msno, 'inner')

In [23]:
sqlCtx.setConf("spark.sql.shuffle.partitions", u"600")

In [27]:
logs_train_test.show(5)

ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1035, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 883, in send_command
    response = connection.send_command(command)
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1040, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:42236)

In [40]:
logs_train_test.orderBy("msno", "date_timestamp")

AnalysisException: "cannot resolve '`msno`' given input columns: [num_50, num_unq, date, num_25, total_secs, num_985, num_75, msno, num_100, msno, date_timestamp];;\n'Sort ['msno ASC NULLS FIRST, date_timestamp#173 ASC NULLS FIRST], true\n+- Join Inner, (msno#12 = msno#219)\n   :- Project [msno#12, date#13, num_25#14, num_50#15, num_75#16, num_985#17, num_100#18, num_unq#19, total_secs#20, convert_date(date#13) AS date_timestamp#173]\n   :  +- Project [msno#12, date#13, num_25#14, num_50#15, num_75#16, num_985#17, num_100#18, num_unq#19, total_secs#20, convert_date(date#13) AS date_timestamp#139]\n   :     +- Project [msno#12, date#13, num_25#14, num_50#15, num_75#16, num_985#17, num_100#18, num_unq#19, total_secs#20, convert_date(date#13) AS date_timestamp#83]\n   :        +- Relation[msno#12,date#13,num_25#14,num_50#15,num_75#16,num_985#17,num_100#18,num_unq#19,total_secs#20] csv\n   +- Union\n      :- Project [msno#219]\n      :  +- Relation[msno#219,is_churn#220] csv\n      +- Project [msno#236]\n         +- Relation[msno#236,is_churn#237] csv\n"

In [28]:
sc.stop()

ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:42236)
Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
/opt/spark/python/pyspark/context.py:413: RuntimeWarning: Unable to cleanly shutdown Spark JVM process. It is possible that the process has crashed, been killed or may also be in a zombie state.
  RuntimeWarning